### ISSUE TITLE
Align web_app_pool and web_app_pool_info attributes

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/microsoft.iis#12]
##### SUMMARY
Currently the `attributes` option for `web_app_pool` flatten the keys for selecting the attribute to set

```yaml
- name: Manage child element and set identity of application pool
  microsoft.iis.web_app_pool:
    name: IdentitiyAppPool
    state: started
    attributes:
      managedPipelineMode: Classic
      processModel.identityType: SpecificUser
```

The `web_app_pool_info` module returns attributes as a dict structure so would be in the following format

```yaml
attributes:
  managedPipelineMode: Classic
  processModel:
    identityType: SpecificUser
```

We should align the behaviours here so that the output of `web_app_pool_info` matches the input for `web_app_pool`. My suggestion would be to change `web_app_pool` to accept a dictionary like the below but happy to talk it through a bit more if there are other ideas.

```yaml
- name: Manage child element and set identity of application pool
  microsoft.iis.web_app_pool:
    name: IdentitiyAppPool
    state: started
    attributes:
      managedPipelineMode: Classic
      processModel:
        identityType: SpecificUser
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
web_app_pool
web_app_pool_info

##### ANSIBLE VERSION
```paste below
N/A
```
